apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.serviceInfo.name }}
  labels:
    app: {{ .Values.serviceInfo.name }}
    chart: {{ template "deployment.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceInfo.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceInfo.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.serviceInfo.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: config-{{ .Values.serviceInfo.name }}
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          ports:
          - name: {{ .Values.serviceInfo.name }}
            containerPort: {{ .Values.service.containerPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: config-{{ .Values.serviceInfo.name }}
          configMap:
            name: {{ .Values.serviceInfo.name }}

