apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceInfo.name }}
  labels:
    app: {{ .Values.serviceInfo.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.serviceInfo.name }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.serviceInfo.name }}
    nodePort: {{ .Values.service.port }}
    
  selector:
    app: {{ .Values.serviceInfo.name }}
