apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceInfo.name }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Values.serviceInfo.name }}
data:
  config.json: |-
    {{ .Files.Get .Values.configMapPath }}