# Default values for deployment.3
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

serviceInfo:
  name: users

image:
  repository: myhay/users
  tag: latest
  pullPolicy: IfNotPresent

configMapPath: "config.json"

service:
  containerPort: 3000
  type: NodePort
  port: 3000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}